services:
  app:
    # Use the pre-built image (Nginx + PHP included)
    build: .
#    image: serversideup/php:8.4-fpm-nginx
    container_name: laravel_app-${APP_ENV}
    restart: always
    environment:
     - AUTORUN_LARAVEL_STORAGE_LINK=true
     - AUTORUN_LARAVEL_MIGRATION=false # Keep this false for manual control in GH Actions
     - PUID=33
     - PGID=33
    volumes:
      # Bind mount your code so git pull works instantly
      - .:/var/www/html
      # Persistent named volumes for your data
#      - storage_data:/var/www/html/storage
#      - public_assets:/var/www/html/public
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=Host(`dev.feuerwehr-quierschied.org`)"
      - "traefik.http.routers.laravel.entrypoints=websecure"
      - "traefik.http.routers.laravel.tls.certresolver=myresolver"
      # IMPORTANT: ServerSideUp listens on 8080 by default
      - "traefik.http.services.laravel.loadbalancer.server.port=8080"

  redis:
    image: redis:7-alpine
    container_name: laravel_redis-${APP_ENV}
    restart: always
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - proxy

  db:
    image: postgres:15-alpine
    container_name: laravel_db-${APP_ENV}
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - proxy

volumes:
  pg_data:
  redis_data:
  public_assets:
  storage_data:

networks:
  proxy:
    external: true